FROM node:12.13.1 as node
FROM ruby:2.7.1

RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    bash \
    build-essential \
    libpq-dev \
    mariadb-client \
    libfontconfig1 && \
    rm -rf /var/lib/apt/lists/*

ENV YARN_VERSION 1.19.1

COPY --from=node /opt/yarn-v$YARN_VERSION /opt/yarn
COPY --from=node /usr/local/bin/node /usr/local/bin/

RUN ln -s /opt/yarn/bin/yarn /usr/local/bin/yarn \
    && ln -s /opt/yarn/bin/yarnpkg /usr/local/bin/yarnpkg

RUN gem install bundler

WORKDIR /app
ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install --jobs 4
COPY . /app

EXPOSE 8888
